pipeline:
  name: my-pipeline

  configuration:
    affinityGroup: build_steps  # Name of the affinity group

  steps:
    - name: build_step1
      # type: script   # You can replace 'script' with other JFrog pipeline step types
      # script: echo "This is the first build step"
      execution:
        onStart:
          - echo "This is the first build step"
      

    - name: build_step2
      type: script
      execution:
        onStart:
          - echo "This is the second build step"


