pipelines:
  - name: MyApprovalGatesPipeline
    steps:
      - name: approvalGatesStep
        type: Bash
        configuration:
          requiresApproval:
            approvers:
              - admin # must be a valid Artifactory user
        execution:
          onExecute:
            - echo "executing step..."
