pipelines:
  - name: Example
    steps:
      - name: step1
        type: Bash
        execution:
          onExecute:
            - echo 'step1'
            - add_run_variables 'var1=a'  # Set var1 as a string

      - name: step2
        type: Bash
        configuration:
          condition: 'var1 =~ "^[a-z]{3,32}$"'  # Use regex to check if var1 matches the pattern
          inputSteps:
            - name: step1
        execution:
          onExecute:
            - echo 'Regex match succeeded'
            - echo $var1
