pipelines:
  - name: Example
    steps:
      - name: step1
        type: Bash
        execution:
          onExecute:
            - echo 'step1'
            - add_run_variables 'var1=1273@Bbcaaaaaakbfwhfgwefwieuhfiwuhfwoufhwoufhwugfwoufgwugfwu'
      - name: step2
        type: Bash
        configuration:
          condition: "var1.startsWith('a') && var1.length <= 32" # Regex approximation
          inputSteps:
            - name: step1
        execution:
          onExecute:
            - echo 'success'
            - echo $var1
