pipelines:
  - name: Example
    steps:
      - name: step1
        type: Bash
        execution:
          onExecute:
            - echo 'step1'
            - add_run_variables 'var1=a'  # Set var1 as a string

      - name: step2
        type: Bash
        configuration:
          inputSteps:
            - name: step1
        execution:
          onExecute:
            - echo "Value of var1: $var1"
            - if [[ "$var1" =~ ^[a-z]{3,32}$ ]]; then 
                echo "Regex match succeeded"; 
              else 
                echo "Regex match failed"; 
                exit 1;  # Optionally fail the step
              fi
