template: true
valuesFilePath: ./values.yml

__globals:
  all_step_status: &all_step_status
    status:
      - success
      - failure
      - skipped
      - cancelled
      - error
      - unstable
      - timeout

  platformUiTestBranch: &platformUiTestBranch 'master'

  commonPostExecutionSection: &commonPostExecutionSection
    onSuccess:
      - stepCommons_on_success --step-status-group=critical_path || echo "[ERROR] stepCommons_on_success returned an error"
      - on_success || echo "[ERROR] on_success returned an error"
    onFailure:
      - on_failure || echo "[ERROR] on_failure returned an error"
      - stepCommons_on_failure --step-status-group=critical_path || echo "[ERROR] stepCommons_on_failure returned an error"
    onComplete:
      - stepCommons_pre_on_complete
      - on_complete || echo "[ERROR] on_complete returned an error"
      - stepCommons_on_complete

  commonBeOnstartSection: &commonBeOnstartSection
    onStart:
      - cd ${res_event_service_e2e_bitbucket_resourcePath}
      - source build/ci/pipelines_step_setup.sh
      - source e2e-tests/build/ci/pipelines_e2e_tests.sh
      - on_start
  commonEnvParameters: &commonEnvParameters
    DEPLOYMENT_TYPE: "cloud"
    EXPIRY: "${DEPLOYMENT_EXPIRY}"
    SHOULD_RUN: "true"
    ARTIFACTORY_VERSION: "${EVENT_TESTS_E2E_ARTI_ONLINE_DOCKER_TAG}"
    CORE_CHART_VERSION: "${res_event_service_arti_bundle_jfrog_docker_online_artifactoryBaseTag}"
    DISTRIBUTION_VERSION: "latestRelease"
    XRAY_VERSION: "latestRelease"
    JFMC_VERSION: "latestRelease"
    PIPELINES_VERSION: "latestRelease"
    XRAY: "false"
    PIPELINES: "false"
    JFMC: "false"
    REGION: "dev-2-euc1"


pipelines:
  - name: event_service_e2e
    configuration:
      environmentVariables:
        readOnly:
          JFROG_CLI_TEMP_DIR: /tmp
          CI: "true"
          MAVEN_OPTS: "'-Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss,SSS -Dmaven.wagon.http.pool=false'"
          MAVEN_CONFIG: "'-P main-test -B -nsu -e'"
          SLACK_MAIN_INTEGRATION: slack_platform_clean_pipeline
          SLACK_MAIN_INTEGRATION_CHANNEL: platform-clean-pipeline
          SLACK_RELEASE_INTEGRATION: slack_platform_release_pipeline
          SLACK_RELEASE_INTEGRATION_CHANNEL: platform-release-pipeline
          SLACK_JFDEV_AGENT_INTEGRATION: jfdev_agent
          GIT_LFS_SKIP_SMUDGE: 1
          EVENT_TESTS_E2E_ARTI_DOCKER_IMAGE:
            default: entplus.jfrog.io/jfrog-docker/jfrog/artifactory-pro
          EVENT_TESTS_E2E_ARTI_DOCKER_TAG:
            default: latestRelease
          EVENT_TESTS_E2E_ARTI_ONLINE_DOCKER_TAG:
            default: latestRelease
          EVENT_TESTS_E2E_EVENT_DOCKER_IMAGE:
            default: entplus.jfrog.io/dev-master-docker-virtual/jfrog/event
          EVENT_TESTS_E2E_EVENT_DOCKER_TAG:
            default: master-20
          EVENT_TESTS_E2E_EVENT_DOCKER_REPO:
            default: "entplus.jfrog.io/${res_event_service_entplus_jfrog_io_docker_image_sourceRepository}"
            description: "The parameter required for CS setup. Example: 'entplus.jfrog.io/dev-master-docker-virtual'"
          DEPLOYMENT_EXPIRY:
            default: "2h"
            description: "Expiry time for the environments will be shut down, 30m, 2h, 1d, 1w ... up to 2w"
          RUN_LOCAL_TEST_SUITE:
            default: 'true'
            values:
              - 'true'
              - 'false'
          RUN_CLOUD_TEST_SUITE:
            default: 'true'
            values:
              - 'true'
              - 'false'
          RUN_FE_TEST_SUITE:
            default: 'true'
            values:
              - 'true'
              - 'false'
      integrations:
        - name: jfdev_agent
        - name: docker_jfrog_io_reader
        - name: entplus_deployer
        - name: entplus_pipelines
        - name: entplus_ci_jfrogdev_org
        - name: entplus_jfrog_io_docker
        - name: slack_dev_foundation_alerts
        - name: slack_platform_clean_pipeline
        - name: slack_platform_release_pipeline
        - name: slack_event_pipe
        - name: sonar_jfrog_info
        - name: jira_jfrog
        - name: jenkins_infra_ci
        - name: github_automation_infra
        - name: devf_embedded_pipelines

    steps:
      - name: trigger_all
        type: Bash
        execution:
          onExecute:
            - echo "Starting full pipeline run."
            - add_run_variables "run_local_test_suite=${RUN_LOCAL_TEST_SUITE}"
            - add_run_variables "run_cloud_test_suite=${RUN_CLOUD_TEST_SUITE}"
            - add_run_variables "run_fe_test_suite=${RUN_FE_TEST_SUITE}"

      - name: event_local_e2e
        type: MvnBuild
        configuration:
          condition: "run_local_test_suite == 'true'"
          sourceLocation: e2e-tests
          configFileLocation: ../build/ci/.conf
          configFileName: maven-config
          mvnCommand: test ${MAVEN_CONFIG}
          inputResources:
              - name: event_service_e2e_bitbucket
                trigger: false
          inputSteps:
            - name: trigger_all
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - 17
        execution:
          <<: *commonBeOnstartSection
          <<: *commonPostExecutionSection

{{ if (regexMatch "^master$|^preRelease/.*|^milestone/.*|^release/.*" "{{gitBranch}}") }}
      - name: deploy_cloud_env
        # Cloud tests are failing because of too many runs that make us hit https://webhook.site rate limits. As a temporary workaround, we disable Cloud tests for all dev branches.
        type: Jenkins
        configuration:
          condition: "run_cloud_test_suite == 'true'"
          timeoutSeconds: 3600
          jenkinsJobName: infra/test/infra-jfrog-frontend-trigger-e2e-env
          inputSteps:
            - name: trigger_all
          outputResources:
            - name: event_cloud_env_props
          buildParameters:
            NAMESPACE: "jevtcloud${run_id}"
            PIPELINES_OUTPUT_RESOURCE: "event_cloud_env_props"
            EXTRA_PARAMS: "master_key=EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
                            artifactory_core_services_enabled=True
                            chart_app_version_unalignment_enabled=true
                            docker_repo_name=${EVENT_TESTS_E2E_EVENT_DOCKER_REPO}
                            conf_core_service_app_version=event;${EVENT_TESTS_E2E_EVENT_DOCKER_TAG}
                            feature_jfconnect_enabled=true"
            DISTRIBUTION: "false"
            <<: *commonEnvParameters

      - name: event_cloud_e2e
        type: MvnBuild
        configuration:
          condition: "run_cloud_test_suite == 'true'"
          environmentVariables:
            ARTIFACTORY_PASSWORD:
              default: password
            ARTIFACTORY_USER:
              default: admin
            BASE_URL:
              default: "${res_event_cloud_env_props_envUrl}/"
            EVENT_TESTS_E2E_PROVISIONING_RESOURCE_FACTORY_MODE:
              default: cloud
            JOIN_KEY:
              default: EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
          sourceLocation: e2e-tests
          configFileLocation: ../build/ci/.conf
          configFileName: maven-config
          mvnCommand: test -P cloud-test -B -nsu -e
          inputResources:
            - name: event_service_e2e_bitbucket
              trigger: false
            - name: event_cloud_env_props
          inputSteps:
            - name: deploy_cloud_env
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - 17
        execution:
          <<: *commonBeOnstartSection
          <<: *commonPostExecutionSection
{{ end }}

      - name: deploy_cloud_fe_env
        type: Jenkins
        configuration:
          condition: "run_fe_test_suite == 'true'"
          timeoutSeconds: 3600
          jenkinsJobName: infra/test/infra-jfrog-frontend-trigger-e2e-env
          inputSteps:
            - name: trigger_all
          outputResources:
            - name: event_fe_env_props
          buildParameters:
            NAMESPACE: "jevtfecloud${run_id}"
            PIPELINES_OUTPUT_RESOURCE: "event_fe_env_props"
            EXTRA_PARAMS: "master_key=0098a3db926121d657955ebb9461483c
                            artifactory_core_services_enabled=True
                            chart_app_version_unalignment_enabled=true
                            docker_repo_name=${EVENT_TESTS_E2E_EVENT_DOCKER_REPO}
                            conf_core_service_app_version=event;${EVENT_TESTS_E2E_EVENT_DOCKER_TAG}
                            feature_jfconnect_enabled=true"
            DISTRIBUTION: "true"
            <<: *commonEnvParameters
      - name: cloud_fe_e2e
        type: TriggerPipeline
        configuration:
          environmentVariables:
            E2E_ENV_URL: ${res_event_fe_env_props_envUrl}
            E2E_TAGS: "@cloud"
            MFE_SERVICE: "event"
            MFE_SERVICE_BRANCH: {{gitBranch}}
          inputResources:
            - name: event_frontend_bitbucket
              trigger: false
            - name: event_fe_env_props
          pipelineName: frontend_e2e
          stepName: e2e_test
          branchName: *platformUiTestBranch
        execution:
          onStart:
            - task: jfdev-ci-commons/setup-step-commons@v0.0.1
              input:
                JFDEV_CI_COMMONS_DEFAULT_VERSION: {{ .Values.jfdevCiCommonsDefaultVersion }}
                PROJECT_ROOT_DIR: "${res_event_frontend_bitbucket_resourcePath}"
              id: setup_step_commons
            - source "${res_event_frontend_bitbucket_resourcePath}/${OUT_setup_step_commons_PIPE_STEP_COMMONS_PATH}"
            - |
              set_trigger_payload pipelineVariables "E2E_ENV_URL=${E2E_ENV_URL}" \
                "E2E_TAGS=${E2E_TAGS}" \
                "MFE_SERVICE=${MFE_SERVICE}" \
                "MFE_SERVICE_BRANCH=${MFE_SERVICE_BRANCH}" \
            - stepCommons_load_script build/ci/pipelines_automation_utils.sh
            - on_start || echo "[INFO] on_start is not defined"
          <<: *commonPostExecutionSection
