pipelines:
  - name: Example
    steps:
      - name: step1
        type: Bash
        execution:
          onExecute:
            - echo 'step1'
            - add_run_variables 'var1=1273@Bbcaaaaaakbfwhfgwefwieuhfiwuhfwoufhwoufhwugfwoufgwugfwu'
      - name: step2
        type: Bash
        configuration:
          condition: 'ARTIFACTORY_DOCKER_IMAGE_TAG != "" && (SHOULD_EXECUTE_SAAS_E2E == "true" || ALLOW_RUN_SINGLE_STEPS == "true")'
          inputSteps:
            - name: step1
        execution:
          onExecute:
            - echo 'success'
            - echo $var1
            - echo ($ARTIFACTORY_DOCKER_IMAGE_TAG != "" && ($SHOULD_EXECUTE_SAAS_E2E == "true" || $ALLOW_RUN_SINGLE_STEPS == "true"))
