pipelines:
  - name: my_pipeline1234567
    configuration:
      environmentVariables:
        readOnly:
          env1: pipe_value1
          env2:
            default: pipe_value2
            description: This is env2 description
            values:
              - pipe_value2
              - pipe_value3
              - pipe_value4
    steps:
      - name: my_step
        type: Bash
        configuration:
         environmentVariables:
            {{ if hasPrefix "preRelease" "{{gitBranch}}" }}
            SIGN_EXECUTABLES: "True"
            {{ else }}
            SIGN_EXECUTABLES: "False"
            {{ end }}
            gitBranch: "{{gitBranch}}"
        execution:
          onExecute:
            - echo "test"
            - echo ${SIGN_EXECUTABLES}
            - echo {{gitBranch}}
